apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-priority-class
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: charts/qa-priority-class
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true