  server:
    port: 8081

  integration:
    internal:
      host:
        orchestrator: http://orchestrator:8081
        telegram-bot: http://telegram-bot:8082
        recognizer: http://recognizer:8080
        invest: http://invest:8087

  spring:
    kafka:
      bootstrap-servers: http://localhost:9092
