  server:
    port: 8081

  integration:
    internal:
      host:
        orchestrator: http://localhost:8081
        telegram-bot: http://localhost:8082
        recognizer: http://localhost:8080
        invest: http://localhost:8087

  spring:
    kafka:
      bootstrap-servers: http://localhost:9092
