service:
  port: 80
  targetPort: 8080

deployment:
  replicas: 1
  containers:
    image: provectuslabs/kafka-ui
    imageTag: latest
    containerPort: 8080
    env:
      - name: KAFKA_CLUSTERS_0_NAME
        value: "my-cluster"
      - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
        value: "kafka-service:9092"
      - name: MANAGEMENT_HEALTH_LDAP_ENABLED
        value: "FALSE"
      - name: SERVER_SERVLET_CONTEXT_PATH
        value: "/kafka-ui"
      - name: AUTH_TYPE
        value: "LOGIN_FORM"
      - name: SPRING_SECURITY_USER_NAME
        value: "{{ KAFKA_UI_USER }}"
      - name: SPRING_SECURITY_USER_PASSWORD
        value: "{{ KAFKA_UI_PASSWORD }}"