apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: postgres-exporter
          image: {{ .Values.deployment.containers.image }}
          ports:
            - containerPort: {{ .Values.deployment.containers.containerPort }}
          env:
            {{- range .Values.deployment.containers.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
