{{- define "shared.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  {{- range $path, $_ := .Files.Glob "**.yml" }}
  {{ $path }}: |
  {{- range $.Files.Lines $path }}
    {{ . }}
  {{- end }}
  {{- end }}
{{- end -}}