{{- define "shared.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.deployment.replicas }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - image: {{ .Values.deployment.containers.image }}:{{ .Values.deployment.containers.imageTag }}
          imagePullPolicy: {{ .Values.deployment.containers.pullPolicy }}
          name: {{ .Chart.Name }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            requests:
              memory: {{ .Values.deployment.containers.requestsMemory }}
            limits:
              memory: {{ .Values.deployment.containers.limitsMemory }}
          env:
            {{- range .Values.deployment.containers.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.deployment.containers.envFrom }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name | quote }}
                  key: {{ .valueFrom.secretKeyRef.key | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.deployment.containers.containerPort }}
      priorityClassName: {{ .Values.deployment.priorityClassName }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secretProviderClass.name }}
{{- end -}}