{{- define "shared.secret" -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.serviceAccountName }}-token
  namespace: {{ .Values.serviceAccountNamespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccountName | quote }}
{{- end -}}