{{- define "shared.secretproviderclass" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Values.secretProviderClass.namespace }}
spec:
  provider: vault
  secretObjects:
    {{- range .Values.secretProviderClass.objects }}
    - data:
        - key: {{ .secretKey | quote }}
          objectName: {{ .objectName | quote }}
      secretName: {{ .objectName | quote }}
      type: Opaque
    {{- end }}
  parameters:
    vaultAddress: {{ .Values.secretProviderClass.vaultAddress | quote }}
    roleName: {{ .Values.secretProviderClass.roleName | quote }}
    objects: |
      {{- range .Values.secretProviderClass.objects }}
        - objectName: {{ .objectName | quote }}
          secretPath: {{ .secretPath | quote }}
          secretKey: {{ .secretKey | quote }}
      {{- end }}
{{- end -}}