{{- define "shared.secretproviderclass" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.secretProviderClass.vaultAddress | quote }}
    roleName: {{ .Values.secretProviderClass.roleName | quote }}
    objects: |
      {{- range .Values.secretProviderClass.objects }}
        - objectName: {{ .objectName | quote }}
          secretPath: {{ .secretPath | quote }}
          secretKey: {{ .secretKey | quote }}
      {{- end }}
{{- end -}}