{{- define "shared.secretproviderclass" -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  {{- if .Values.secretProviderClass.namespace }}
  namespace: {{ .Values.secretProviderClass.namespace }}
  {{- end }}
spec:
  provider: vault
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.secretName }}
      type: Opaque
      data:
    {{- range .Values.secretProviderClass.objects }}
        - key: {{ .secretKey | quote }}
          objectName: {{ .objectName | quote }}
    {{- end }}

    - secretName: registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        - key: docker-config-json
          objectName: docker-config-json
  parameters:
    vaultAddress: {{ .Values.secretProviderClass.vaultAddress | quote }}
    roleName: {{ .Values.secretProviderClass.roleName | quote }}
    objects: |
      {{- range .Values.secretProviderClass.objects }}
        - objectName: {{ .objectName | quote }}
          secretPath: {{ .secretPath | quote }}
          secretKey: {{ .secretKey | quote }}
      {{- end }}
{{- end -}}