{{- define "shared.serviceaccount" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  {{- if .Values.serviceAccountNamespace }}
  namespace: {{ .Values.serviceAccountNamespace }}
  {{- end }}
{{- end -}}