version: '3.1'

services:
  orchestrator-db:
    container_name: orchestrator-db
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrator-db
    restart: always

  telegram-bot-db:
    container_name: telegram-bot-db
    image: postgres:14.1-alpine
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram-bot-db
    restart: always

  payment-db:
    container_name: payment-db
    image: postgres:14.1-alpine
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments-db
    restart: always