services:
  orchestrator-service:
    container_name: orchestrator
    image: ghcr.io/nekromant322/orchestrator:latest
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      ORCHESTRATOR_DB_USER: ${ORCHESTRATOR_DB_USER}
      ORCHESTRATOR_DB_PASSWORD: ${ORCHESTRATOR_DB_PASSWORD}
      ORCHESTRATOR_DB_HOST: ${ORCHESTRATOR_DB_HOST}
      ORCHESTRATOR_DB_PORT: ${ORCHESTRATOR_DB_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
      JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      INTERNAL_KEY_HEADER: ${INTERNAL_KEY_HEADER}
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  recognizer-service:
    container_name: recognizer
    image: ghcr.io/nekromant322/recognizer:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      _JAVA_OPTIONS: -Xmx512m
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      WIT_AI_TOKEN: ${WIT_AI_TOKEN}
      INTERNAL_KEY_HEADER: ${INTERNAL_KEY_HEADER}
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  payment-service:
    container_name: payment
    image: ghcr.io/nekromant322/payment:latest
    restart: unless-stopped
    ports:
      - '8084:8084'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      INTERNAL_KEY_HEADER: ${INTERNAL_KEY_HEADER}
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  wit-ai-go-proxy-service:
    container_name: wit-ai-go-proxy
    image: ghcr.io/nekromant322/wit_ai_go_proxy:latest
    restart: unless-stopped
    ports:
      - '3333:3333'
    environment:
      WIT_AI_TOKEN: ${WIT_AI_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  telegram-bot-service:
    container_name: telegram-bot
    image: ghcr.io/nekromant322/telegram_bot:latest
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      _JAVA_OPTIONS: -Xmx256m
      TELEGRAM_BOT_DB_USER: ${TELEGRAM_BOT_DB_USER}
      TELEGRAM_BOT_DB_PASSWORD: ${TELEGRAM_BOT_DB_PASSWORD}
      TELEGRAM_BOT_DB_HOST: ${TELEGRAM_BOT_DB_HOST}
      TELEGRAM_BOT_DB_PORT: ${TELEGRAM_BOT_DB_PORT}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      SPRING_APPLICATION_PROFILE: ${SPRING_APPLICATION_PROFILE}
      ORCHESTRATOR_HOST: ${ORCHESTRATOR_HOST}
      INTERNAL_KEY_HEADER: ${INTERNAL_KEY_HEADER}
    logging:
      driver: "json-file"
      options:
        max-size: 50m