apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-landing
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend-landing=overregistry.ru/overmoney-frontend-landing:latest
    argocd-image-updater.argoproj.io/frontend-landing.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend-landing.force-update: 'true'
    argocd-image-updater.argoproj.io/frontend-landing.helm.image-name: deployment.containers.image
    argocd-image-updater.argoproj.io/frontend-landing.helm.image-tag: deployment.containers.imageTag
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: charts/frontend-landing
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: -1
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 23h
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true