apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=nekromant322/overmoney-frontend:latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.force-update: 'true'
    argocd-image-updater.argoproj.io/frontend.helm.image-name: deployment.containers.image
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: deployment.containers.imageTag
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: charts/kafka-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true