apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegram-bot
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: telegram-bot=nekromant322/overmoney-telegram-bot:latest
    argocd-image-updater.argoproj.io/telegram-bot.update-strategy: digest
    argocd-image-updater.argoproj.io/telegram-bot.force-update: 'true'
    argocd-image-updater.argoproj.io/telegram-bot.helm.image-name: deployment.containers.image
    argocd-image-updater.argoproj.io/telegram-bot.helm.image-tag: deployment.containers.imageTag
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: charts/telegram-bot
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 23h
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true