secretProviderClass:
  name: vault-default
  roleName: default
  secretName: default
  objects:
    - objectName: "default-grafana-password"
      secretPath: "secret/default"
      secretKey: "default-grafana-password"
    - objectName: "default-private-registry-username"
      secretPath: "secret/default"
      secretKey: "default-private-registry-username"
    - objectName: "default-private-registry-password"
      secretPath: "secret/default"
      secretKey: "default-private-registry-password"
    - objectName: "docker-config-json"
      secretPath: "secret/default"
      secretKey: "docker-config-json"