apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-default
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: argocd/overmoney-cluster/default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true