apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-default
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: argocd/overmoney-cluster/default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: -1
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 23h
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true