apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-qa
  namespace: argo-cd
  annotations:
#    argocd-image-updater.argoproj.io/image-list: recognizer-qa=nekromant322/overmoney-recognizer-qa:latest, orchestrator-qa=overmoney-orchestrator-qa:latest, telegram-bot-qa=overmoney-telegram-bot-qa:latest
#    argocd-image-updater.argoproj.io/recognizer-qa.update-strategy: digest
#    argocd-image-updater.argoproj.io/orchestrator-qa.update-strategy: digest
#    argocd-image-updater.argoproj.io/telegram-bot-qa.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: recognizer-qa=nekromant322/overmoney-recognizer-qa, orchestrator-qa=overmoney-orchestrator-qa, telegram-bot-qa=overmoney-telegram-bot-qa
    argocd-image-updater.argoproj.io/recognizer-qa.update-strategy: newest-build
    argocd-image-updater.argoproj.io/orchestrator-qa.update-strategy: newest-build
    argocd-image-updater.argoproj.io/telegram-bot-qa.update-strategy: newest-build
    argocd-image-updater.argoproj.io/pull-policy: Always
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: qa
    path: argocd/overmoney-cluster/applications-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true