environment: prod
rules:
  - host: overmoney.tech
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orchestrator-service
            port:
              number: 80
      - path: /sse/open-stream
        pathType: Prefix
        backend:
          service:
            name: orchestrator-service
            port:
              number: 80
      - path: /landing
        pathType: Prefix
        backend:
          service:
            name: frontend-landing-service
            port:
              number: 80
      - path: /front
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /kafka-ui
        pathType: ImplementationSpecific
        backend:
          service:
            name: kafka-ui-service
            port:
              number: 80
annotations:
  nginx.ingress.kubernetes.io/affinity: "cookie"
  nginx.ingress.kubernetes.io/session-cookie-name: "sse-affinity"
  nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
  nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"