environment: prod
rules:
  - host: overmoney.tech
    paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: orchestrator-service
            port:
              number: 80
      - path: /landing
        pathType: Prefix
        backend:
          service:
            name: frontend-landing-service
            port:
              number: 80
      - path: /front
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /kafka-ui
        pathType: ImplementationSpecific
        backend:
          service:
            name: kafka-ui-service
            port:
              number: 80