environment: argo-cd
tls:
  - hosts:
      - argo-cd.overmoneytest.online
    secretName: argo-cd-tls-secret
rules:
  - host: overmoneytest.online
    paths:
      - path: /argo-cd
        pathType: Prefix
        backend:
          service:
            name: 'argo-cd-argocd-server'
            port:
              number: 80
annotations:
  nginx.ingress.kubernetes.io/ssl-redirect: false
  nginx.ingress.kubernetes.io/backend-protocol: HTTP
  cert-manager.io/cluster-issuer: letsencrypt-staging