apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-qa
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: qa
    path: charts/ingress
    helm:
      valueFiles:
        - values-qa.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true