apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-qa
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: qa
    path: charts/kafka
    helm:
      valueFiles:
        - values-qa.yaml
  syncPolicy:
    automated: {}
    retry:
      limit: -1
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 23h
    syncOptions:
      - CreateNamespace=true