apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchestrator-qa
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: orchestrator-qa=nekromant322/overmoney-orchestrator-qa
    argocd-image-updater.argoproj.io/orchestrator-qa.update-strategy: newest-build
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: qa
    path: charts/orchestrator
    helm:
      valueFiles:
        - values-qa.yaml
      parameters:
        - name: deployment.containers.imageTag
          value: latest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true