apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-exporter-telegram-qa
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: qa
    path: charts/postgres-exporter-telegram
    helm:
      valueFiles:
        - values-qa.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true