apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qa-priority-class
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: charts/priority-class
    helm:
      valueFiles:
        - values-qa.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true