service:
  port: 80
  targetPort: 8080

deployment:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    image: nekromant322/overmoney-invest
    imageTag: latest
    pullPolicy: Always
    containerPort: 8081
    requestsMemory: "128Mi"
    limitsMemory: "256Mi"
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: INTERNAL_KEY_HEADER
        value: "{{ INTERNAL_KEY_HEADER }}"
