deployment:
  replicas: 1
  containers:
    image: nekromant322/overmoney-invest
    containerPort: 8081
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
    envFrom:
      - name: INTERNAL_KEY_HEADER
        valueFrom:
          secretKeyRef:
            name: prod
            key: internal-key-header
    volumes:
      - name: secrets-store-inline
        volumeMountPath: "/mnt/secrets-store"
        readOnly: true
  priorityClassName: prod-priority-class
secretProviderClass:
  name: vault-prod

hostsNeeded: false