server:
  port: 8082


orchestrator:
  host: overridetech.ru

integration:
  internal:
    host:
      orchestrator: http://localhost:8081
      recognizer: http://localhost:8080

spring:
  kafka:
    bootstrap-servers: http://localhost:9092