server:
  port: 8082


orchestrator:
  host: overridetech.ru

integration:
  internal:
    host:
      orchestrator: http://orchestrator:8081
      recognizer: http://recognizer:8080

spring:
  kafka:
    bootstrap-servers: http://localhost:9092