apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/nekromant322/OverMoney.git
    targetRevision: HEAD
    path: charts/prometheus
    helm:
      parameters:
        - name: serviceAccountNamespace
          value: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true