persistentVolumeClaim:
  requestsStorage: 10Gi

servicePort: 9092
serviceTargetPort: 9092

deployment:
  strategy:
    type: Recreate # Нужно из-за привязки PVC OneToOne - нет возможности законнектить одновременно две кафки, поэтому будет даунтайм
  containers:
    name: broker
    image: apache/kafka
    imageTag: 3.7.0
    pullPolicy: IfNotPresent
    containerPort: 9092
    requestsMemory: "512Mi"
    limitsMemory: "1Gi"
    env:
      - name: KAFKA_ENABLE_KRAFT
        value: "yes"
      - name: KAFKA_PROCESS_ROLES
        value: "broker,controller"
      - name: KAFKA_NODE_ID
        value: "1"
      - name: KAFKA_CONTROLLER_QUORUM_VOTERS
        value: "1@localhost:9093"
      - name: KAFKA_LISTENERS
        value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      - name: KAFKA_ADVERTISED_LISTENERS
        value: "PLAINTEXT://kafka-service:9092"
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      - name: KAFKA_CONTROLLER_LISTENER_NAMES
        value: "CONTROLLER"
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: "PLAINTEXT"
      - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        value: "1"
      - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
        value: "1"
      - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
        value: "1"
      - name: KAFKA_HEAP_OPTS
        value: "-Xms512m -Xmx1g"
    volumes:
      - name: kafka-logs
        persistentVolumeClaimName: kafka-pvc
        volumeMountPath: /var/lib/kafka/logs
  priorityClassName: prod-priority-class