exports:
  data:
    servicePort: 80
    serviceTargetPort: 8080
    deployment:
      replicas: 2
      minReadySeconds: 15
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      containers:
        imageTag: latest # TODO replace with ArgoCD Image Updater
        pullPolicy: Always
        requestsMemory: "256Mi"
        limitsMemory: "512Mi"
        containerPort: 8080
    serviceAccountName: vault-kms
    secretProviderClass:
      vaultAddress: http://hashicorp-vault.vault.svc:8200/