service:
  port: 80
  targetPort: 8080

deployment:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    imageTag: latest
    pullPolicy: Always
    requestsMemory: "256Mi"
    limitsMemory: "512Mi"
    containerPort: 8080