apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.deployment.replicas }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: {{ .Values.deployment.containers.image }}:{{ .Values.deployment.containers.imageTag }}
          imagePullPolicy: {{ .Values.deployment.containers.pullPolicy }}
          name: {{ .Chart.Name }}
          resources:
            requests:
              memory: {{ .Values.deployment.containers.requestsMemory }}
            limits:
              memory: {{ .Values.deployment.containers.limitsMemory }}
          env:
            {{- range .Values.deployment.containers.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}

          ports:
            - containerPort: {{ .Values.deployment.containers.containerPort }}