environment: ${ENVIRONMENT:dev}

server:
  port: 8080

service:
  transaction:
    processing: kafka

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://${PAYMENT_DB_HOST:localhost}:${PAYMENT_DB_PORT:5436}/payments-db
    username: ${PAYMENT_DB_USER:postgres}
    password: ${PAYMENT_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  liquibase:
    enabled: false
    change-log: /db/changelog/db.changelog-master.xml

  profiles:
    active: ${SPRING_APPLICATION_PROFILE:dev}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.override.dto
        spring.json.use.type.headers: false

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,gitInfo
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

authorization-header:
  header-value: ${INTERNAL_KEY_HEADER:X-INTERNAL-KEY}

mask-log-spring-boot-starter:
  maskedFields:
    - x-internal-key

yookassa:
  shop-id: ${YOOKASSA_SHOP_ID}
  secret-key: ${YOOKASSA_SECRET_KEY}