servicePort: 3000
serviceTargetPort: 3000

deployment:
  containers:
    image: grafana/grafana
    imageTag: latest
    containerPort: 3000
    env:
      - name: GF_SECURITY_ADMIN_USER
        value: "grafana"
      - name: GF_SERVER_ROOT_URL
        value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      - name: GF_SERVER_SERVE_FROM_SUB_PATH
        value: "true"
      - name: GF_SECURITY_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: default
            key: default-grafana-password
      - name: telegram-bot-token-grafana
        valueFrom:
          secretKeyRef:
            name: default
            key: telegram-bot-token-grafana

    volumeMounts:
      - name: grafana-provisioning
        mountPath: /etc/grafana/provisioning/
        readOnly: true

  volumes:
    - name: grafana-provisioning
      configMap:
        name: grafana-config

  priorityClassName: prod-priority-class

secretProviderClass:
  name: vault-default