servicePort: 3000
serviceTargetPort: 3000

deployment:
  containers:
    image: grafana/grafana
    imageTag: latest
    containerPort: 3000
    env:
      - name: GF_SECURITY_ADMIN_USER
        value: "grafana"
      - name: GF_SERVER_ROOT_URL
        value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      - name: GF_SERVER_SERVE_FROM_SUB_PATH
        value: "true"
    envFrom:
      - name: GF_SECURITY_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: default
            key: default-grafana-password
    volumes:
      - name: secrets-store-inline
        volumeMountPath: "/mnt/secrets-store"
        readOnly: true
      - name: grafana-datasources
        volumeMountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
        subPath: datasources.yaml
      - name: grafana-alerting
        volumeMountPath: "/etc/grafana/provisioning/alerting/default-alert-rules.yaml"
        subPath: default-alert-rules.yaml
      - name: grafana-notifiers
        volumeMountPath: "/etc/grafana/provisioning/notifiers/default-contact-points.yaml"
        subPath: default-contact-points.yaml
      - name: grafana-notification-templates
        volumeMountPath: "/etc/grafana/notification-templates/telegram-template.tmpl"
        subPath: telegram-template.tmpl
  priorityClassName: prod-priority-class

grafana-datasources:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service:9090
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: "5s"
          httpMethod: "POST"

grafana-alerting:
  default-alert-rules.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: Critical Alerts
        folder: Alerts
        interval: 10s
        rules:
          - uid: dejlx8yk10flse
            title: System CPU Usage > 80
            condition: B
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: fejkzilfrpy4gf
                model:
                  disableTextWrap: false
                  editorMode: code
                  expr: system_cpu_usage * 100
                  fullMetaSearch: false
                  includeNullMetadata: true
                  instant: true
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: false
                  refId: A
                  useBackend: false
              - refId: B
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: B
                  type: threshold
            noDataState: Alerting
            execErrState: Alerting
            for: 1m
            annotations:
              description: Использование CPU > 80%
              summary: Высокая нагрузка CPU
            isPaused: false
            notification_settings:
              receiver: Telegram
          - uid: cejm0732h5khsb
            title: Heap Used > 80
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 3600
                  to: 0
                datasourceUid: fejkzilfrpy4gf
                model:
                  adhocFilters: []
                  datasource:
                    type: prometheus
                    uid: fejkzilfrpy4gf
                  editorMode: code
                  expr: jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"} * 100
                  format: time_series
                  instant: true
                  interval: ""
                  intervalFactor: 1
                  intervalMs: 30000
                  legendFormat: ""
                  maxDataPoints: 100
                  range: false
                  refId: A
                  step: 14400
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: threshold
            dashboardUid: spring_boot_21
            panelId: 58
            noDataState: Alerting
            execErrState: Alerting
            for: 1m
            annotations:
              __dashboardUid__: spring_boot_21
              __panelId__: "58"
              description: Использование памяти JVM > 80%
              summary: Высокая загрузка памяти
            isPaused: false
            notification_settings:
              receiver: Telegram

grafana-notifiers:
  default-contact-points.yaml: |
    apiVersion: 1
    contactPoints:
      - name: Telegram
        receivers:
          - type: telegram
            settings:
              bottoken: "$__env{telegram-bot-token-grafana}"
              chatid: "-4795149880"
              message: '{{ template "telegram.message" . }}'

grafana-notification-templates:
  telegram-template.tmpl: |
    {{ define "alert_list" }}
    {{ range . }}
    {{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} <b>{{ .Labels.alertname }}</b>
    {{ if .Labels.instance }}• <b>Инстанс:</b> {{ .Labels.instance }}{{ end }}
    {{ if .Labels.job }}• <b>Сервис:</b> {{ .Labels.job }}{{ end }}
    {{ range .Annotations.SortedPairs }}• <b>{{ .Name }}:</b> {{ .Value }}
    {{ end }}{{ end }}{{ end }}

    {{ define "telegram.message" }}
    {{ if gt (len .Alerts.Firing) 0 }}<b>🚨 КРИТИЧЕСКИЕ АЛЕРТЫ</b>
    {{ template "alert_list" .Alerts.Firing }}{{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}<b>✅ РЕШЕННЫЕ АЛЕРТЫ</b>
    {{ template "alert_list" .Alerts.Resolved }}{{ end }}
    {{ end }}

secretProviderClass:
  name: vault-default