apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging # change to letsencrypt-prod-key when ready
spec:
  acme:
    email: devops@overmoneytest.online
    server: https://acme-staging-v02.api.letsencrypt.org/directory # change to https://acme-v02.api.letsencrypt.org/directory when ready
    privateKeySecretRef:
      name: letsencrypt-staging-key # change to letsencrypt-prod-key when ready
    solvers:
      - http01:
          ingress:
            class: nginx