deployment:
  containers:
    image: overregistry.ru/overmoney-recognizer
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=50.0"
      - name: ENVIRONMENT
        value: "prod"
    envFrom:
      - name: INTERNAL_KEY_HEADER
        valueFrom:
          secretKeyRef:
            name: prod
            key: internal-key-header
      - name: DEEPSEEK_AUTH_TOKEN
        valueFrom:
          secretKeyRef:
            name: prod
            key: deepseek-auth-token
    volumes:
      - name: secrets-store-inline
        volumeMountPath: "/mnt/secrets-store"
        readOnly: true
  priorityClassName: prod-priority-class

secretProviderClass:
  name: vault-prod