deployment:
  replicas: 1
  containers:
    image: nekromant322/overmoney-recognizer-qa
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=50.0"
      - name: VAULT_ADDR
        value: "http://vault-0.vault:8200"
    envFrom:
      - name: INTERNAL_KEY_HEADER
        valueFrom:
          secretKeyRef:
            name: qa
            key: internal-key-header
    secretTemplate: |
      {{ with secret "secrets/qa" -}}
        export internal-key-header={{ .Data.internal-key-header}}
      {{- end }}
  priorityClassName: qa-priority-class
serviceAccountName: vault-kms # vault-kms
serviceAccountNamespace: qa
secretProviderClass:
  name: vault-qa
  vaultAddress: http://vault.vault.svc:8200
  roleName: qa
  objects:
    - objectName: "internal-key-header"
      secretPath: "secrets/qa"
      secretKey: "internal-key-header"
