deployment:
  replicas: 1
  containers:
    image: nekromant322/overmoney-recognizer-qa
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=50.0"
    envFrom:
      - name: INTERNAL_KEY_HEADER
        valueFrom:
          secretKeyRef:
            name: qa
            key: internal-key-header
  priorityClassName: qa-priority-class
secretProviderClass:
  name: vault-qa