deployment:
  replicas: 1
  containers:
    image: nekromant322/overmoney-recognizer-qa
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=50.0"
    envFrom:
      - name: INTERNAL_KEY_HEADER
        valueFrom:
          secretKeyRef:
            name: qa
            key: internal-key-header
    secretTemplate: |
      {{- with secret "secret/qa" -}}
        export INTERNAL_KEY_HEADER={{ .Data.internal-key-header }}
      {{- end -}}
  priorityClassName: qa-priority-class
serviceAccountName: vault-kms # vault-kms is working
serviceAccountNamespace: qa # qa is working
secretProviderClass:
  name: vault-qa
  namespace: qa # qa is working
  vaultAddress: http://vault.vault:8200
  roleName: qa
  objects:
    - objectName: "internal-key-header"
      secretPath: "secret/qa"
      secretKey: "internal-key-header"
