deployment:
  containers:
    image: overregistry.ru/overmoney-recognizer-qa
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=50.0"
      - name: ENVIRONMENT
        value: "qa"
    envFrom:
      - name: INTERNAL_KEY_HEADER
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-internal-key-header
    volumes:
      - name: secrets-store-inline
        volumeMountPath: "/mnt/secrets-store"
        readOnly: true
      - name: secrets-store-inline-default
        volumeMountPath: "/mnt/secrets-store/default"
        readOnly: true
  priorityClassName: qa-priority-class

secretProviderClass:
  - name: vault-qa
  - name: vault-default
