service:
  port: 80
  targetPort: 8080

deployment:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  containers:
    image: nekromant322/overmoney-orchestrator
    imageTag: latest
    pullPolicy: Always
    containerPort: 8080
    requestsMemory: "256Mi"
    limitsMemory: "512Mi"
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: TELEGRAM_BOT_TOKEN
        value: "8094666153:AAFei9psVilLDocwJlmxFoeZzMLXJq1QRa8"
      - name: TELEGRAM_BOT_NAME
        value: "TestOvermoneyBot"
      - name: INTERNAL_KEY_HEADER
        value: "{{ INTERNAL_KEY_HEADER }}"
      - name: JWT_ACCESS_KEY
        value: "{{ JWT_ACCESS_KEY }}"
      - name: JWT_REFRESH_KEY
        value: "{{ JWT_REFRESH_KEY }}"
      - name: ORCHESTRATOR_DB_HOST
        value: "194.87.237.197"
      - name: ORCHESTRATOR_DB_PORT
        value: "5433"
      - name: ORCHESTRATOR_DB_USER
        value: "testmoney"
      - name: ORCHESTRATOR_DB_PASSWORD
        value: "testmoney"
  priorityClassName: qa-priority-class