deployment:
  replicas: 1
  containers:
    image: nekromant322/overmoney-orchestrator-qa
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: TELEGRAM_BOT_TOKEN
        value: "{{ QA_TELEGRAM_BOT_TOKEN }}"
      - name: TELEGRAM_BOT_NAME
        value: "TestOvermoneyBot"
      - name: INTERNAL_KEY_HEADER
        value: "{{ INTERNAL_KEY_HEADER }}"
      - name: JWT_ACCESS_KEY
        value: "{{ JWT_ACCESS_KEY }}"
      - name: JWT_REFRESH_KEY
        value: "{{ JWT_REFRESH_KEY }}"
      - name: ORCHESTRATOR_DB_HOST
        value: "194.87.237.197"
      - name: ORCHESTRATOR_DB_PORT
        value: "{{ QA_ORCHESTRATOR_DB_PORT }}"
      - name: ORCHESTRATOR_DB_USER
        value: "{{ QA_ORCHESTRATOR_DB_USER }}"
      - name: ORCHESTRATOR_DB_PASSWORD
        value: "{{ QA_ORCHESTRATOR_DB_PASSWORD }}"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=50.0"
  priorityClassName: qa-priority-class