deployment:
  registry: overregistry.ru
  containers:
    image: overregistry.ru/overmoney-orchestrator-qa
    env:
      - name: SPRING_APPLICATION_PROFILE
        value: "prod"
      - name: TELEGRAM_BOT_NAME
        value: "TestOvermoneyBot"
      - name: ORCHESTRATOR_DB_HOST
        value: "194.87.237.197"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=70.0 -XX:MinRAMPercentage=50.0"
      - name: ENVIRONMENT
        value: "qa"
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: 'kafka-service.qa.svc'
    envFrom:
      - name: INTERNAL_KEY_HEADER
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-internal-key-header
      - name: TELEGRAM_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-telegram-bot-token
      - name: JWT_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-jwt-access-key
      - name: JWT_REFRESH_KEY
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-jwt-refresh-key
      - name: ORCHESTRATOR_DB_PORT
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-orchestrator-db-port
      - name: ORCHESTRATOR_DB_USER
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-orchestrator-db-user
      - name: ORCHESTRATOR_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: qa
            key: qa-orchestrator-db-password
    volumes:
      - name: secrets-store-inline
        volumeMountPath: "/mnt/secrets-store"
        readOnly: true
  priorityClassName: qa-priority-class

secretProviderClass:
  name: vault-qa