deployment:
  containers:
    env:
      - name: DATA_SOURCE_URI
        value: "194.87.237.197:5435/telegram-bot-db?sslmode=disable"
      - name: DATA_SOURCE_USER
        value: "{{ QA_TELEGRAM_BOT_DB_USER }}"
      - name: DATA_SOURCE_PASS
        value: "{{ QA_TELEGRAM_BOT_DB_PASSWORD }}"