servicePort: 2181
serviceTargetPort: 2181

deployment:
  containers:
    image: confluentinc/cp-zookeeper
    imageTag: 7.0.1
    pullPolicy: IfNotPresent
    containerPort: 2181
    env:
      - name: ZOOKEEPER_CLIENT_PORT
        value: "2181"
      - name: ZOOKEEPER_TICK_TIME
        value: "2000"
      - name: JVMFLAGS
        value: "-Dos.memory.max=512m"
  priorityClassName: prod-priority-class