deployment:
  containers:
    env:
      - name: ZOOKEEPER_CLIENT_PORT
        value: "2181"
      - name: ZOOKEEPER_TICK_TIME
        value: "2000"
  priorityClassName: qa-priority-class
secretProviderClass:
  name: vault-qa