name: Build & Push & Deploy to k8s cluster

on:
  push:
    branches:
      - qa

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      recognizer: ${{ steps.filter.outputs.recognizer }}
#      orchestrator: ${{ steps.filter.outputs.orchestrator }}
#      telegram-bot: ${{ steps.filter.outputs.telegram-bot }}
#      invest: ${{ steps.filter.outputs.invest }}
#      wit-ai-go-proxy: ${{ steps.filter.outputs.wit-ai-go-proxy }}
#      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            recognizer:
              - 'recognizer_service/**'
#            orchestrator:
#              - 'orchestrator_service/**'
#            telegram-bot:
#              - 'telegram_bot_service/**'
#            invest:
#              - 'invest_service/**'
#            wit-ai-go-proxy:
#              - 'wit_ai_go_proxy/**'
#            frontend:
#              - 'frontend/**'

#  build-and-push-images:
#    name: Build & Push images to DockerHub
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Login to DockerHub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#        with:
#          version: v0.7.0

#      - name: Orchestrator Build and Push to Dockerhub
#        if: ${{ needs.detect-changes.outputs.orchestrator == 'true' }}
#        uses: docker/build-push-action@v2
#        with:
#          file: /orchestrator_service/Dockerfile
#          push: true
#          tags: nekromant322/overmoney-orchestrator

#      - name: Recognizer Build and Push to Dockerhub
#        if: ${{ needs.detect-changes.outputs.recognizer == 'true' }}
#        uses: docker/build-push-action@v2
#        with:
#          file: /recognizer_service/Dockerfile
#          push: true
#          tags: nekromant322/overmoney-recognizer

#      - name: Telegram Bot Build and Push to Dockerhub
#        if: ${{ needs.detect-changes.outputs.telegram-bot == 'true' }}
#        uses: docker/build-push-action@v2
#        with:
#          file: /telegram_bot_service/Dockerfile
#          push: true
#          tags: nekromant322/overmoney-telegram-bot
#
#      - name: Invest Build and Push to Dockerhub
#        if: ${{ needs.detect-changes.outputs.invest == 'true' }}
#        uses: docker/build-push-action@v2
#        with:
#          file: /invest_service/Dockerfile
#          push: true
#          tags: nekromant322/overmoney-invest
#
#      - name: Wit ai go proxy Build and Push to Dockerhub
#        if: ${{ needs.detect-changes.outputs.wit-ai-go-proxy == 'true' }}
#        uses: docker/build-push-action@v2
#        with:
#          file: /wit_ai_go_proxy/Dockerfile
#          push: true
#          tags: nekromant322/overmoney-wit-ai-go-proxy
#      - name: Frontend Build and Push to Dockerhub
#        if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
#        uses: docker/build-push-action@v2
#        with:
#          file: /frontend/Dockerfile
#          push: true
#          tags: nekromant322/overmoney-frontend

  deploy-to-k8s:
    name: Deploy to Kubernetes Cluster
    runs-on: ubuntu-latest
#    needs: [build-and-push-images]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject secrets in resource manifests
        uses: none0nfg/yaml-secrets-injector@v0.0.1
        with:
          inject_files: |-
            charts/recognizer/values-qa.yaml
            charts/ingress/values-qa.yaml
            charts/zookeeper/values-qa.yaml
            charts/kafka/values-qa.yaml
#            charts/postgres-exporter-orchestrator/values-qa.yaml
#            charts/postgres-exporter-telegram/values-qa.yaml
#            charts/orchestrator/values-qa.yaml
#            charts/telegram-bot/values-qa.yaml
#            charts/admin-user/values-qa.yaml
#            charts/invest/values-qa.yaml
#            charts/wit-ai-go-proxy/values-qa.yaml
#            charts/kafka-ui/values-qa.yaml
#            charts/frontend/values-qa.yaml
#            charts/prometheus/values-qa.yaml
          secrets: ${{ toJSON(secrets) }}

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBER_STATIC_CONFIG }}" | base64 --decode > $HOME/.kube/config
          kubectl config use-context default

      - name: Test Kubernetes Connection
        run: kubectl cluster-info

      - name: Helm Dry Run Recognizer Service
        run: |-
          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/recognizer/values-qa.yaml recognizer ./charts/recognizer
          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/ingress/values-qa.yaml ingress-qa ./charts/ingress
          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/zookeeper/values-qa.yaml zookeeper ./charts/zookeeper
          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/kafka/values-qa.yaml kafka ./charts/kafka
#          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/orchestrator/values-qa.yaml orchestrator ./charts/orchestrator
#          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/telegram-bot/values-qa.yaml telegram-bot ./charts/telegram-bot
#          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/frontend/values-qa.yaml frontend ./charts/frontend
#          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/invest/values-qa.yaml invest ./charts/invest
#          helm upgrade --install --atomic --dry-run=server -n qa -f ./charts/wit-ai-go-proxy/values-qa.yaml wit-ai-go-proxy ./charts/wit-ai-go-proxy


      - name: Helm Deploy Recognizer Service
        run: |-
          helm upgrade --install --atomic -n qa -f ./charts/recognizer/values-qa.yaml recognizer ./charts/recognizer
          helm upgrade --install --atomic -n qa -f ./charts/ingress/values-qa.yaml ingress-qa ./charts/ingress
          helm upgrade --install --atomic -n qa -f ./charts/zookeeper/values-qa.yaml zookeeper ./charts/zookeeper
#          helm upgrade --install --atomic -n qa -f ./charts/kafka/values-qa.yaml kafka ./charts/kafka
#          helm upgrade --install --atomic -n qa -f ./charts/orchestrator/values-qa.yaml orchestrator ./charts/orchestrator
#          helm upgrade --install --atomic -n qa -f ./charts/telegram-bot/values-qa.yaml telegram-bot ./charts/telegram-bot
#          helm upgrade --install --atomic -n qa -f ./charts/frontend/values-qa.yaml frontend ./charts/frontend
#          helm upgrade --install --atomic -n qa -f ./charts/invest/values-qa.yaml invest ./charts/invest
#          helm upgrade --install --atomic -n qa -f ./charts/wit-ai-go-proxy/values-qa.yaml wit-ai-go-proxy ./charts/wit-ai-go-proxy

#      - name: Conditional Rollout Restarts
#        run: |
#          if [ "${{ needs.detect-changes.outputs.orchestrator }}" == "true" ]; then
#            kubectl rollout restart deployment sa-orchestrator -n qa
#          fi
#
#          if [ "${{ needs.detect-changes.outputs.recognizer }}" == "true" ]; then
#            kubectl rollout restart deployment sa-recognizer -n qa
#          fi
#
#          if [ "${{ needs.detect-changes.outputs.telegram-bot }}" == "true" ]; then
#            kubectl rollout restart deployment sa-telegram-bot -n qa
#          fi
#
#          if [ "${{ needs.detect-changes.outputs.invest }}" == "true" ]; then
#            kubectl rollout restart deployment sa-invest -n qa
#          fi
#
#          if [ "${{ needs.detect-changes.outputs.wit-ai-go-proxy }}" == "true" ]; then
#            kubectl rollout restart deployment sa-wit-ai-go-proxy -n qa
#          fi
#
#          if [ "${{ needs.detect-changes.outputs.frontend }}" == "true" ]; then
#            kubectl rollout restart deployment frontend -n qa
#          fi