name: Build & Push & Deploy to k8s cluster

on:
  push:
    branches:
      - master

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      recognizer: ${{ steps.filter.outputs.recognizer }}
      orchestrator: ${{ steps.filter.outputs.orchestrator }}
      telegram-bot: ${{ steps.filter.outputs.telegram-bot }}
      invest: ${{ steps.filter.outputs.invest }}
      wit-ai-go-proxy: ${{ steps.filter.outputs.wit-ai-go-proxy }}
      frontend: ${{ steps.filter.outputs.frontend }}
      frontend-landing: ${{ steps.filter.outputs.frontend-landing }}
      payment: ${{ steps.filter.outputs.payment }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            recognizer: ['recognizer_service/**']
            orchestrator: ['orchestrator_service/**']
            telegram-bot: ['telegram_bot_service/**']
            shared-chart: ['charts/shared/**']
            invest: ['invest_service/**']
            wit-ai-go-proxy: ['wit_ai_go_proxy/**']
            frontend: ['frontend/**']
            frontend-landing: ['frontend_landing/**']
            payment: ['payment_service/**']

  build-and-push-images:
    name: Build & Push images to DockerHub
    runs-on: ubuntu-latest
    needs: [detect-changes]
    steps:
      - uses: actions/checkout@v4
      - name: Login to private Docker registry (overregistry.ru)
        uses: docker/login-action@v3
        with:
          registry: overregistry.ru
          username: ${{ secrets.DOCKER_PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PRIVATE_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Recognizer Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.recognizer == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./recognizer_service/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-recognizer

      - name: Orchestrator Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.orchestrator == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./orchestrator_service/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-orchestrator

      - name: Telegram Bot Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.telegram-bot == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./telegram_bot_service/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-telegram-bot

      - name: Invest Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.invest == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./invest_service/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-invest

      - name: Wit ai go proxy Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.wit-ai-go-proxy == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./wit_ai_go_proxy/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-wit-ai-go-proxy

      - name: Frontend Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-frontend

      - name: Frontend Landing Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.frontend-landing == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./frontend_landing/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-frontend-landing
          build-args: |
            BUILD_CMD=build-production

      - name: Payment Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.payment == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./payment_service/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-payment