name: Build & Push & Deploy to k8s cluster QA namespace

on:
  push:
    branches:
      - qa

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      recognizer: ${{ steps.filter.outputs.recognizer }}
      orchestrator: ${{ steps.filter.outputs.orchestrator }}
      telegram-bot: ${{ steps.filter.outputs.telegram-bot }}
      frontend: ${{ steps.filter.outputs.frontend }}
      invest: ${{ steps.filter.outputs.invest }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            recognizer: ['recognizer_service/**']
            orchestrator: ['orchestrator_service/**']
            telegram-bot: ['telegram_bot_service/**']
            frontend: [frontend/**']
            invest: ['invest_service/**']

  build-and-push-images:
    name: Build & Push images to DockerHub
    runs-on: ubuntu-latest
    needs: [detect-changes]
    steps:
      - uses: actions/checkout@v4
      - name: Login to private Docker registry (overregistry.ru)
        uses: docker/login-action@v3
        with:
          registry: overregistry.ru
          username: ${{ secrets.DOCKER_PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PRIVATE_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Recognizer Build and Push to overregistry.ru
        if: ${{ needs.detect-changes.outputs.recognizer == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /recognizer_service/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-recognizer-qa

      - name: Orchestrator Build and Push to Dockerhub
        if: ${{ needs.detect-changes.outputs.orchestrator == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /orchestrator_service/Dockerfile
          push: true
          tags: nekromant322/overmoney-orchestrator-qa

      - name: Telegram Bot Build and Push to Dockerhub
        if: ${{ needs.detect-changes.outputs.telegram-bot == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /telegram_bot_service/Dockerfile
          push: true
          tags: nekromant322/overmoney-telegram-bot-qa

      - name: Invest Build and Push to Dockerhub
        if: ${{ needs.detect-changes.outputs.invest == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /invest_service/Dockerfile
          push: true
          tags: nekromant322/overmoney-invest-qa

      - name: Frontend Build and Push to Dockerhub
        if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
        uses: docker/build-push-action@v2
        with:
          file: /frontend/Dockerfile
          push: true
          tags: nekromant322/overmoney-frontend-qa